theme: jekyll-theme-minimal
title: Zixiang Ma
description: Minimal is a theme for GitHub Pages.
show_downloads: false
logo: /resources/images/Profile.jpg
# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/mmistakes
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/mmistakes
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/mmistakes
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square